<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-HGRS86I" name="testng.testngAnnotation.TestNGExamples" tests="5" failures="0" timestamp="30 三月 2018 11:26:50 GMT" time="1.032" errors="1">
  <testcase name="sampleTestCase" time="0.002" classname="testng.testngAnnotation.TestNGExamples"/>
  <testcase name="registerAccount" time="0.004" classname="testng.testngAnnotation.TestNGExamples"/>
  <testcase name="executetimeOut" time="1.021" classname="testng.testngAnnotation.TestNGExamples">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testng.testngAnnotation.TestNGExamples.executetimeOut() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testng.testngAnnotation.TestNGExamples.executetimeOut() didn't finish within the time-out 1000
]]>
    </error>
  </testcase> <!-- executetimeOut -->
  <testcase name="login" time="0.003" classname="testng.testngAnnotation.TestNGExamples"/>
  <testcase name="sendEmail" time="0.002" classname="testng.testngAnnotation.TestNGExamples"/>
</testsuite> <!-- testng.testngAnnotation.TestNGExamples -->
